settings:
  menu:
    title: "&#facc15ᴋʜᴏ Đồ ᴄá ɴʜâɴ"
    rows: 3
    display-material: ENDER_CHEST
    item-name: "&#facc15ᴋʜᴏ Đồ số %number%"
    item-lore:
      - ""
      - "&#facc15| &#ffffffᴄʟɪᴄᴋ Để ᴍở ᴋʜᴏ đồ"
      - ""
  vault:
    title: "ᴋʜᴏ ᴠᴀᴜʟᴛ #%number%"
    rows: 6
  sounds:
    menu-open: BLOCK_ENDER_CHEST_OPEN
    vault-open: BLOCK_ENDER_CHEST_OPEN
    vault-close: BLOCK_ENDER_CHEST_CLOSE
messages:
  mode:
    chat: true
    actionbar: true
  no-permission: "&#ff0812ʙạɴ ᴋʜôɴɢ ᴄó ǫᴜʏềɴ ᴍở ᴋʜᴏ đồ số %number%!"
