settings:
  menu:
    rows: 3
    title: "&#facc15ᴠᴀᴜʟᴛꜱ (ᴘᴀɢᴇ 1)"
    display-material: "ENDER_CHEST"
    item-name: "&#facc15ᴠᴀᴜʟᴛ %number%"
    item-lore:
      - ""
      - "§eᴄʟɪᴄᴋ ᴛᴏ ᴏᴘᴇɴ"
      - ""
  vault:
    rows: 6
    title: "§0Kho đồ số %number%"
  sounds:
    menu-open: "BLOCK_CHEST_OPEN"
    vault-open: "BLOCK_ENDER_CHEST_OPEN"
    vault-close: "BLOCK_ENDER_CHEST_CLOSE"
messages:
  no-permission: "§cBạn không có quyền sử dụng ᴠᴀᴜʟᴛ %number%!"
